const sites = () => {
  return [
    { // TODO
      host: "tiktok",
      url: null,
      match: /^www.tiktok.com$/,
      selector: null,
    },
    { // TODO
      host: "coursera",
      url: null,
      match: /^www.coursera.org$/,
      selector: null,
    },
    { // TODO
      host: "udemy",
      url: "https://www.udemy.com",
      match: null,
      selector: null,
    },
    {
      host: "youtube",
      url: "https://youtu.be/",
      match: /^(www.|m.)?youtube(-nocookie)?.com$/,
      selector: ".html5-video-container",
    },
    { // mobile
      host: "twitch",
      url: "https://twitch.tv/",
      match: /^m.twitch.tv$/,
      selector: "main > div > section > div > div > div",
    },
    {
      host: "twitch",
      url: "https://twitch.tv/",
      match: /^(www.)?twitch.tv$/,
      selector: ".video-ref",
    },
    {
      host: "xvideos",
      url: "https://www.xvideos.com/",
      match: /^www.xvideos.com$/,
      selector: ".video-bg-pic",
    },
    {
      host: "pornhub",
      url: "https://rt.pornhub.com/view_video.php?viewkey=",
      match: /^[a-z]+.pornhub.com$/,
      selector: ".mgp_videoWrapper",
    },
    {
      host: "vk",
      url: "https://vk.com/video?z=",
      match: /^(www.|m.)?vk.(com|ru)$/,
      selector: ".videoplayer_media",
    },
    {
      host: "vimeo",
      url: "https://vimeo.com/",
      match: /^(player.)?vimeo.com$/,
      selector: ".player",
    },
    {
      host: "nine_gag",
      utl: "https://9gag.com/gag/",
      match: /^9gag.com$/,
      selector: ".video-post",
    },
    {
      host: "coub",
      url: "https://coub.com/view/",
      match: /^coub.com$/,
      selector: ".viewer__player",
    },
    {
      host: "bitchute",
      url: "https://www.bitchute.com/video/",
      match: /^(www.)?bitchute.com$/,
      selector: ".plyr__video-wrapper",
    },
    {
      host: "rutube",
      url: "https://rutube.ru/video/",
      match: /^rutube.ru$/,
      selector: ".video-player > div > div > div:nth-child(2)",
    },
    { // embed
      host: "rutube",
      url: "https://rutube.ru/video/",
      match: /^rutube.ru$/,
      selector: "#app > div > div",
    },
    {
      host: "bilibili",
      url: "https://www.bilibili.com/video/",
      match: /^(www|m).bilibili.com$/,
      selector: ".bpx-player-video-wrap",
    },
    { // old (/blackboard/webplayer/embed-old.html)
      host: "bilibili",
      url: "https://www.bilibili.com/video/",
      match: /^(www|m).bilibili.com$/,
      selector: null,
    },
    {
      host: "twitter",
      url: "https://twitter.com/i/status/",
      match: /^twitter.com$/,
      selector: 'div[data-testid="videoComponent"] > div:nth-child(1) > div',
    },
    {
      host: "mail_ru",
      url: "https://my.mail.ru/",
      match: /^my.mail.ru$/,
      selector: "#b-video-wrapper",
    },
    { // Sites host Invidious. I tested the performance only on invidious.kevin.rocks, youtu.be and inv.vern.cc
      host: "invidious",
      url: "https://youtu.be/",
      match: [
        "invidious.snopyta.org",
        "yewtu.be",
        "invidious.kavin.rocks",
        "vid.puffyan.us",
        "invidious.namazso.eu",
        "inv.riverside.rocks",
        "yt.artemislena.eu",
        "invidious.flokinet.to",
        "invidious.esmailelbob.xyz",
        "y.com.sb",
        "invidious.nerdvpn.de",
        "inv.vern.cc",
        "invidious.slipfox.xyz",
        "invidio.xamh.de",
        "invidious.dhusch.de",
      ],
      selector: "#player",
    },
    { // Sites host Piped. I tested the performance only on piped.video
      host: "piped",
      url: "https://youtu.be/",
      match: [
        "piped.video",
        "piped.tokhmi.xyz",
        "piped.moomoo.me",
        "piped.syncpundit.io",
        "piped.mha.fi",
        "watch.whatever.social",
        "piped.garudalinux.org",
        "efy.piped.pages.dev",
        "watch.leptons.xyz",
        "piped.lunar.icu",
        "yt.dc09.ru",
        "piped.mint.lgbt",
        "il.ax",
        "piped.privacy.com.de",
        "piped.esmailelbob.xyz",
        "piped.projectsegfau.lt",
        "piped.in.projectsegfau.lt",
        "piped.us.projectsegfau.lt",
        "piped.privacydev.net",
        "piped.palveluntarjoaja.eu",
        "piped.smnz.de",
        "piped.adminforge.de",
        "piped.qdi.fi",
        "piped.hostux.net",
        "piped.chauvet.pro",
        "piped.jotoma.de",
        "piped.pfcd.me",
        "piped.frontendfriendly.xyz",
      ],
      selector: ".shaka-video-container",
    }
  ];
};

export default sites();
